### ISSUE TITLE
Additional analysis Russian Elections

### ISSUE THREAD

**Issue by Shadyelgewily** [khakhalin/Sketches#1]
The voting percentages could additionally be studied applying the Newcomb–Benford law: https://en.wikipedia.org/wiki/Benford%27s_law

See also the following paper: https://www.researchgate.net/publication/237341643_Election_Forensics_Vote_Counts_and_Benford's_Law

**Comment by khakhalin** [comment]
I am pretty sure I have a table in the repo that is even called "Benford's law" :) It's just that I didn't realize that I can look at 2-digit combinations, and 1-digit combinations weren't too interesting... But it's a good point! [Here's a thread by Kamil Pastor](https://twitter.com/pastor_kamil/status/1280273903370330112) where he applies Benford's law to 2-digit combinations for this data, and finds some cool results :)
